version: "3.4"

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.7.2
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.2.3
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092
    healthcheck:
      test: "bash -c 'echo QUIT | nc -w 1 localhost 9092'"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - zookeeper
    networks:
      - kafka-net

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
networks:
  kafka-net:
  db-net: